with open("sample.txt", 'a') as tables:  # use 'w' to create a new file, 'a' to modify existing file
    for i in range(2, 13):  # This list is created once
        for j in range(1, 13):  # This list is created EACH time a new list is generated by i, and is nested within it
            print("{1:>2} times {0} is {2}".format(i, j, i * j), file=tables)
        print("-" * 20, file=tables)
